#pragma once

void board_init(void);

#define BOARD_BQ_INT_PORT GPIOA
#define BOARD_BQ_INT_PIN LL_GPIO_PIN_0
#define BOARD_BQ_INT_IRQ EXTI0_IRQn

#define BOARD_CABLE_DET_PORT GPIOF
#define BOARD_CABLE_DET_PIN LL_GPIO_PIN_1
#define BOARD_CABLE_DET_IRQ EXTI1_IRQn

#define BOARD_DEBUG_N_PORT GPIOB
#define BOARD_DEBUG_N_PIN LL_GPIO_PIN_6

#define BOARD_LED_PORT GPIOA
#define BOARD_LED_PIN LL_GPIO_PIN_10

#define BOARD_MAX_INT_PORT GPIOA
#define BOARD_MAX_INT_PIN LL_GPIO_PIN_5
#define BOARD_MAX_INT_IRQ EXTI9_5_IRQn

#define BOARD_PWR_BTN_PORT GPIOA
#define BOARD_PWR_BTN_PIN LL_GPIO_PIN_2
#define BOARD_PWR_BTN_IRQ EXTI2_IRQn

#define BOARD_PWR_ON_PORT GPIOA
#define BOARD_PWR_ON_PIN LL_GPIO_PIN_7

#define BOARD_USB_DP_PORT GPIOA
#define BOARD_USB_DP_PIN LL_GPIO_PIN_12

#define BOARD_USB_DM_PORT GPIOA
#define BOARD_USB_DM_PIN LL_GPIO_PIN_11

#define BOARD_SCL_PORT GPIOA
#define BOARD_SCL_PIN LL_GPIO_PIN_15
#define BOARD_SCL_AF LL_GPIO_AF_4

#define BOARD_SDA_PORT GPIOB
#define BOARD_SDA_PIN LL_GPIO_PIN_7
#define BOARD_SDA_AF LL_GPIO_AF_4

#define BOARD_VOL_DOWN_PORT GPIOB
#define BOARD_VOL_DOWN_PIN LL_GPIO_PIN_3
#define BOARD_VOL_DOWN_IRQ EXTI3_IRQn

#define BOARD_VOL_UP_PORT GPIOB
#define BOARD_VOL_UP_PIN LL_GPIO_PIN_4
#define BOARD_VOL_UP_IRQ EXTI4_IRQn

#define BOARD_I2C I2C1